name: Docker Build

on:
  workflow_dispatch:
  push:
    tags:
    branches:
      - main
      - development
      - feature/*
      - fix/*

jobs:
  docker-build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Wait for checks to succeed
        uses: lewagon/wait-on-check-action@master
        with:
          ref: ${{ github.ref }}
          check-name: 'Docker build'
          running-workflow-name: 'Verify'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allowed-conclusions: success
      - name: Checkout
        uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: Login to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
          name: docker-image
          path: /image/docker-image.tar
#      - name: Download Docker image artifact
#        uses: actions/download-artifact@v2
#        with:
#          name: docker-image
#          path: /image/docker-image.tar
      - name: Load Docker image
        run: docker load -i /image/docker-image.tar
      - name: Push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
      - name: Tag & Push branch image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
      - name: Tag & Push latest image
        if: github.ref_name == 'main'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:latest
