name: Docker Build

on:
  workflow_dispatch:
  push:
    tags:
    branches:
      - main
      - development
      - feature/*
      - fix/*

jobs:
  docker-build:
    name: 'Docker bot push'
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Wait for checks to succeed
        uses: lewagon/wait-on-check-action@master
        with:
          ref: ${{ github.ref }}
          check-name: 'Docker build'
          running-workflow-name: 'Verify'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allowed-conclusions: success
      - name: Checkout
        uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v3
      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: verify.yml
          workflow_conclusion: success
          name: docker-image
#      - name: Download Docker image artifact
#        uses: actions/download-artifact@v2
#        with:
#          name: docker-image
#          path: /image/docker-image.tar
      - name: Load Docker image
        run: docker load -i ./docker-image.tar
      - name: Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
      - name: Tag & Push branch image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
      - name: Tag & Push latest image
        if: github.ref_name == 'main'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:latest

  docs-build:
    name: 'Docker docs push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docs.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-docs:${{ github.sha }}
      - name: Tag & Push branch image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docs.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-docs:${{ github.sha }}
            ghcr.io/${{ github.repository }}-docs:${{ github.ref_name }}
      - name: Tag & Push latest image
        if: github.ref_name == 'main'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docs.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-docs:${{ github.sha }}
            ghcr.io/${{ github.repository }}-docs:latest
